name: Atualizar EPG

on:
  schedule:
    - cron: '0 */6 * * *'   # Corre de 6 em 6 horas
  workflow_dispatch:         # Para correres manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo na gh-pages
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          ref: gh-pages  # ⚡️ Branch onde o Pages vai buscar

      - name: Configurar Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Instalar gunzip
        run: sudo apt-get update && sudo apt-get install -y gzip

      - name: Fazer download do EPG .gz
        run: curl -L -o epg.xml.gz https://epgshare01.online/epgshare01/epg_ripper_PT1.xml.gz

      - name: Descomprimir EPG
        run: gunzip -f epg.xml.gz

      - name: Commit & Push para gh-pages com GITHUB_TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add epg.xml
          git commit -m "Atualizar EPG automaticamente" || echo "Nada para commitar"

          echo "⚡ Branch atual:"
          git branch
          echo "⚡ Remotes configurados:"
          git remote -v

          # Força o remote a usar o token
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git

          git push origin gh-pages
