name: Atualizar EPG

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        ref: gh-pages  # OU a branch certa!

    - name: Configurar Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Instalar gunzip
      run: sudo apt-get update && sudo apt-get install -y gzip

    - name: Fazer download do EPG .gz
      run: curl -L -o epg.xml.gz https://epgshare01.online/epgshare01/epg_ripper_PT1.xml.gz

    - name: Descomprimir
      run: gunzip -f epg.xml.gz

    - name: Commit & Push
      run: |
        git add epg.xml
        git commit -m "EPG atualizado" || echo "Nada para commitar"
        git push origin gh-pages
